### ISSUE TITLE
To import the module

### ISSUE THREAD

**Issue by Clemenard** [kaelhem/avrbro#2]
I tried to run your sample code, but when i run 
`import avrbro from 'avrbro';`
 i get some error :
`Uncaught TypeError: Failed to resolve module specifier "avrbro". Relative references must start with either "/", "./", or "../".`
VSCode give me that hint when i check the problematic line : 
`Le fichier de déclaration du module 'avrbro' est introuvable. 'c:/wamp64/www/myProject/node_modules/avrbro/dist/avrbro.js' a implicitement un type 'any'.
  Essayez 'npm install @types/avrbro' s'il existe, ou ajoutez un nouveau fichier de déclaration (.d.ts) contenant 'declare module 'avrbro';'`, 
but theses two solution don't work.

Any idea?

**Comment by kaelhem** [comment]
Hello,
to run the sample code, all you need to do is : 
+ clone the repo
+ cd into the 'avrbro-master' directory
+ launch a webserver from this point (like https://www.npmjs.com/package/serve for exemple, it's really easy, with this one you just type `serve` in the terminal)
+ use chrome (because it's chrome only AFAIK) and activate the experimental feature named `#enable-experimental-web-platform-features`

and it should works.

Let me know if these steps are not working for you.

**Comment by Clemenard** [comment]
I aim to use it for https://fr.vittascience.com/arduino, who is coded in javascript+jquery. I encountered that bug while pasting the sample code in my file managing serial api interactions, after using `npm i avrbro --save`. 

I'll try first your steps to run the demo, thanks

**Comment by kaelhem** [comment]
OK. If you don't transpile your code with babel or a similar tool, I think you can import the script with old good fashion.
just include it in your html like this:
`<script type="text/javascript" src="/node-modules/dist/avrbro.js"></script>`

Then avrbro should be available as a global var.

**Comment by Clemenard** [comment]
I understand my problem now. 
When calling `import avrbro from 'avrbro';` it was searching a file `../avrbro/dist/avrbro.js`
In your sample.html the path is `.. /avrbro/dist/avrbro.m.js`
After changing it it works, thanks for the help

**Comment by kaelhem** [comment]
Glad to hear that!
